# Generated by Django 2.2 on 2020-02-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('playlist_group', 'playlist_id'), name='unique_constraint_group_playlist'),
        ),
    ]
