# Generated by Django 2.2 on 2020-02-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_auto_20200221_1535'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playlist',
            name='unique_constraint_group_playlist',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_group',
        ),
        migrations.AddField(
            model_name='playlist',
            name='groups',
            field=models.ManyToManyField(related_name='playlists', to='spotify.PlaylistGroup'),
        ),
    ]
