# Generated by Django 2.2 on 2020-02-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_auto_20200221_1750'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('playlist_id',), name='unique_constraint_playlist_id'),
        ),
    ]
