# Generated by Django 2.2 on 2020-02-22 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_auto_20200221_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='login.User'),
        ),
    ]
