# Generated by Django 2.2 on 2020-02-22 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_auto_20200221_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_groups', to='login.User'),
        ),
    ]
