# Generated by Django 2.2 on 2020-02-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_auto_20200221_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistgroup',
            name='user',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='PlaylistGroup',
        ),
    ]
