# Generated by Django 2.2 on 2020-02-23 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0006_auto_20200219_1405'),
        ('spotify', '0008_auto_20200222_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_groups', to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(related_name='playlists', to='spotify.PlaylistGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='login.User')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playlistgroup',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_constraint_group_name'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('spotify_id', 'user'), name='unique_constraint_playlist_id_user'),
        ),
    ]
