# Generated by Django 2.2 on 2020-02-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0009_auto_20200222_1625'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.CheckConstraint(check=models.Q(spotify_id__ne=''), name='spotify_id_not_empty'),
        ),
    ]
