# Generated by Django 2.2 on 2020-02-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_id',
            field=models.IntegerField(default=0),
        ),
    ]
