# Generated by Django 2.2 on 2020-02-19 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_spotify_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
