# Generated by Django 2.2 on 2020-02-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200225_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spotify_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
